#!/bin/bash
rm -f /tmp/html.tar
tar cvf /tmp/html.tar \
help.html \
dyn_help.html \
index.html \
mkpuz.html \
cmd_list.pdf \
cmds.html \
scmds.html \
undocumented_cmds.html \
mkclues_index.html \
bee/index.html \
kitt/index.html \
css \
pics \
js \
mktar \
goo10k-7.txt \
osx_usd_words-7.txt \
words23.html \
apple-touch-icon.png \
favicon-32x32.png \
favicon-16x16.png \
android-chrome-192x192.png \
android-chrome-512x512.png \
site.webmanifest
