#!/bin/bash
rm -f /tmp/html.tar
tar cvf /tmp/html.tar \
help.html \
dyn_help.html \
index.html \
mkpuz.html \
cmd_list.pdf \
cmds.html \
scmds.html \
mkclues_index.html \
css \
pics \
js \
mktar \
goo10k-7.txt \
osx_usd_words-7.txt
