#!/bin/bash
rm /tmp/html.tar
tar cvf /tmp/html.tar \
apple.html \
cgi_style.css \
help.html \
index.html \
mkpuz.html \
style_cmd.css \
style.css \
windows.html \
js \
mktar \
goo10k-7.txt \
osx_usd_words-7.txt

# these will not change
#nytbee_cmd.html
#nytbee_cmd.pl
