#!/bin/bash
rm /tmp/html.tar
tar cvf /tmp/html.tar \
apple.html \
cgi_style.css \
help.html \
index.html \
mkpuz.html \
style_cmd.css \
style.css \
windows.html \
cycle.jpg \
js \
mktar

# these will not change
#nytbee_cmd.html
#nytbee_cmd.pl
