#!/bin/bash
rm /tmp/html.tar
tar cvf /tmp/html.tar \
apple.html \
cgi_style.css \
help.html \
index.html \
mkpuz.html \
nytbee_cmd.html \
nytbee_cmd.pl \
style_cmd.css \
style.css \
windows.html \
cycle.jpg \
mktar
