#!/usr/bin/env perl
use strict;
use warnings;
if (! -f 'nytbee_test.pl') {
    die "not initialized\n";
}
my $dif = qx!diff nytbee.pl nytbee_test.pl | grep -v '^[0-9]' | grep -v nytbee_test.pl | grep -v nytbee.pl!;
$dif =~ s{---\n}{}xmsg;
if (!$dif) {
    print "no change yet\n";
}
else {
    open my $pipe, '|-', '/usr/bin/less';
    print {$pipe} $dif;
}
