#!/usr/bin/perl
use strict;
use warnings;

# a poor man's CGI:
print "Content-Type: text/html; charset=ISO-8859-1\n\n";
my $n = $ENV{PATH_INFO};
$n =~ s{\A /}{}xms;

use BeeUtil qw/
    ip_id
    uniq_chars
/;
my $ip_id = ip_id();
my $fname = "community_puzzles/$n.txt";

if (! -f $fname) {
    print "no such puzzle: CP$n\n";
    exit;
}
my $href = do $fname;

if ($ip_id ne $href->{ip_id}) {
    print "you did not create CP$n\n";
    exit;
}

my $seven = $href->{seven};
my $center = $href->{center};
my @lets = uniq_chars($seven);
my %was_checked = map { $_ => 1 } @{$href->{words}};
my $regex = qr{[^$seven]}xms;
print <<"EOH";
<html>
<head>
<link rel='stylesheet' type='text/css' href='http://logicalpoetry.com/nytbee/cgi_style.css'/>
</head>
<body>
<h1>Editing CP$n <span class=step_name>Words</span></h1>
For the seven letters \U$seven\E and center letter <span class=center>\U$center\E</span> we have identified the qualified words AND the words you chose before.
<p>
Check the words you want to include in the puzzle and press Submit at the bottom.  Make sure you include at least one pangram. They are colored <span class=red>red</span>.

<p>
<form action=/cgi-bin/edit_cp_clues method=POST>
<input type=hidden name=CPn value=$n>
<h2>Qualified words used in previous NYT Bee Puzzles:</h2>
You can, of course, UNcheck these words, if you wish.
<p>
EOH
open my $in, '<', 'pwords.txt';
LINE:
while (my $line = <$in>) {
    chomp $line;
    if ($line !~ $regex) {
        if (index($line, $center) >= 0) {
            my $Line = ucfirst $line;
            my $checked = $was_checked{$line}? ' checked': '';
            print "<input type=checkbox name=ok value=$line$checked>&nbsp; ";
            my @uchars = uniq_chars($line);
            if (@uchars == 7) {
                print "<span class=red>$Line</span>";
            }
            else {
                print $Line;
            }
            print "<br>\n";
        }
    }
}
close $in;
print "<h2>More words (qualified but some are rare and esoteric):</h2>\n";
print "Surprisingly, there are many common ordinary words that have not yet been used in any of the NYT puzzles.<p>\n";
open my $in2, '<', 'fourminus.txt';
LINE:
while (my $line = <$in2>) {
    chomp $line;
    if ($line !~ $regex) {
        if (index($line, $center) >= 0) {
            my $Line = ucfirst $line;
            my $checked = $was_checked{$line}? ' checked': '';
            print "<input type=checkbox name=ok value=$line$checked>&nbsp; ";
            my @uchars = uniq_chars($line);
            if (@uchars == 7) {
                print "<span class=red>$Line</span>";
            }
            else {
                print $Line;
            }
            print "<br>\n";
        }
    }
}
close $in2;
print <<'EOH';
<p>
Other qualified words to include:<br><input type=text size=40 name=other_words>
<p>
<button type=submit>Submit</button>
</form>
</body>
</html>
EOH
