#!/usr/bin/perl
use strict;
use warnings;

use CGI;
my $q = CGI->new();
print $q->header();

# we will save the name, location, and word => clues
use Bee_DBH qw/
    add_update_person
/;

use Data::Dumper;

my %params = $q->Vars();
my ($person_id, $ip_id) = add_update_person($params{name}, $params{location});
$params{person_id} = $person_id;
$params{ip_id} = $ip_id;

my $dir = 'community_puzzles';
open my $in, '<', "$dir/last_num.txt";
my $n = <$in>;
close $in;
chomp $n;
++$n;
open my $out, '>', "$dir/last_num.txt";
print {$out} "$n\n";
close $out;

open my $puz, '>', "community_puzzles/$n.txt";
print {$puz} Dumper(\%params);
close $puz;

print <<"EOH";
<html>
<head>
<link rel='stylesheet' type='text/css' href='http://logicalpoetry.com/nytbee/cgi_style.css'/>
</head>
<body>
Finished. &#128077;<br>
You have created an NYT Type Puzzle for the Hivemind Community.
<p>
Your puzzle is #$n.
<p>
Click <a target=_blank href=http://logicalpoetry.com/cgi-bin/nytbee.pl>here</a> to solve it.<br>
You will use the <span class=cmd>CP$n</span> command to open it.
</body>
</html>
EOH
