#!/usr/bin/perl
use strict;
use warnings;
use CGI;
my $q = CGI->new();
print $q->header();

use Date::Simple qw/
    today
/;
my $d8 = today->as_d8();

use BeeUtil qw/
    word_score
    trim
/;

use Bee_DBH qw/
    $dbh
    get_person
/;

use Data::Dumper;
$Data::Dumper::Terse  = 1;
$Data::Dumper::Indent = 0;

my %params = $q->Vars();

# let us assume that the creator of this community puzzle
# will not abandon the creation at this point.
# let's get the next number...
open my $in, '<', 'community_puzzles/last_num.txt';
my $n = <$in>;
close $in;
chomp $n;
++$n;
my $CPn = "CP$n";

my ($ip_id, $person_id, $name, $location) = get_person();
my $sth_ins_clue = $dbh->prepare(<<'EOS');

    INSERT
      INTO bee_clue
           (person_id, date, word, clue)
    VALUES (?, ?, ?, ?)

EOS

my %clues;
CLUE:
for my $k (grep { m! _clue \z!xms } keys %params) {
    my $w = $k;
    $w =~ s{_clue\z}{}xms;
    my $clue = $params{$k};
    $clue =~ s{"}{'}xmsg;       # double quote is troublesome
                                # so just convert to single
                                # use HTML::Entities?
    if ($clue !~ m{\S}xms) {
        # no clue
        next CLUE;
    }
    $sth_ins_clue->execute($person_id, $CPn, $w, $clue);
    $clues{$w} = $clue;
}
my $clues = Dumper(\%clues);
my $seven = $params{seven};
my $center = $params{center};
my $words = $params{words};
my $pangrams = $params{pangrams};
my %is_pangram = map { $_ => 1 } split ' ', $pangrams;
my @words = split ' ', $words;
my $nwords = @words;
my $points = 0;
for my $w (@words) {
    $points += word_score($w, $is_pangram{$w});
}

print <<"EOH";
<html>
<head>
<link rel='stylesheet' type='text/css' href='http://logicalpoetry.com/nytbee/cgi_style.css'/>
</head>
<body>
<h1>Making an NYT Type<br>Spelling Bee Puzzle<br>Step <span class=red>5</span> <span class=step_name>Allowed Hints</span></h1>
<form name=form action=get_allowed_hints method=POST">
<input type=hidden name=seven value='$seven'>
<input type=hidden name=center value='$center'>
<input type=hidden name=words value='$words'>
<input type=hidden name=pangrams value='$pangrams'>
<input type=hidden name=clues value="$clues">
<input type=hidden name=created value='$d8'>
Words: $nwords, Points: $points<br>
Pangrams: <span class=green>$pangrams</span><p>
<p>
What kinds of hints will be allowed for this puzzle?
<ul>
<input type=checkbox name=hint_h value=h checked> Hint Table<p>
<input type=checkbox name=hint_t value=t checked> Two Letter List<p>
<input type=checkbox name=hint_o value=o checked> One Letter List<p>
<input type=checkbox name=hint_d value=d checked> Dictionary Definitions<p>
<input type=checkbox name=hint_v value=v checked> All Reveal Commands (V and E)<p>
<input type=checkbox name=hint_pct value='%'> Limited Reveal Commands (half of the letters)<p>
<input type=checkbox name=hint_1 value=1 checked> Random Hint Table Entry<p>
<input type=checkbox name=hint_2 value=2 checked> Random Two Letter List Entry<p>
<input type=checkbox name=hint_g value=g> Give Up and show all words (G Y)<p>
<button type=submit class=submit>Submit</button>
</ul>
</form>
</body>
</html>
EOH
