#!/usr/bin/perl
use strict;
use warnings;
sub oops {
    die "usage: get_dbm file.dbm key\n";
}
oops unless @ARGV == 2;
my ($hash_file, $key) = @ARGV;
if ($hash_file !~ m{\A \S+[.]dbm \z}xms) {
    $hash_file .= '.dbm';
}
oops unless -f $hash_file;
oops unless defined $key;
use DB_File;
my %hash;
tie %hash, 'DB_File', $hash_file or die "no tie!";
print "$hash{$key}\n";
