#!/usr/bin/perl
use strict;
use warnings;
use CGI;
my $q = CGI->new();
print $q->header();

use Bee_DBH qw/
    get_person
/;

use Date::Simple qw/
    today
/;
my $d8 = today->as_d8();

my %params = $q->Vars();
my $seven = $params{seven};
my $center = $params{center};
my $words = $params{words};
my $pangrams = $params{pangrams};
my $clues = $params{clues};

# what hints?
my $allowed_hints = join '',
                    map  { $params{$_}    }
                    grep { m{\A hint_}xms }
                    keys %params;

my ($ip_id, $person_id, $name, $location) = get_person();

print <<"EOH";
<html>
<head>
<link rel='stylesheet' type='text/css' href='http://logicalpoetry.com/nytbee/cgi_style.css'/>
<script src="http://logicalpoetry.com/nytbee/js/name_location.js"></script>
</head>
<body>
<h1>Making an NYT Type<br>Spelling Bee Puzzle<br>Step <span class=red>6</span> <span class=step_name>Name and Location</span></h1>
<form name=form action=final_mkpuz method=POST onsubmit="return check_name_location();">
<input type=hidden name=seven value='$seven'>
<input type=hidden name=center value='$center'>
<input type=hidden name=words value='$words'>
<input type=hidden name=pangrams value='$pangrams'>
<input type=hidden name=clues value="$clues">
<input type=hidden name=created value='$d8'>
<input type=hidden name=allowed_hints value='$allowed_hints'>

Finally, provide some information about yourself.
<p>
<table cellpadding=5>

<tr>
<th>Name</th>
<td><input type=text name=name id=name value="$name" size=40></td>
</tr>

<tr>
<th>Location</th>
<td><input type=text name=location id=location value="$location" size=40></td>
</tr>

<tr>
<th>&nbsp;</th>
<td style="text-align: left"><button class=submit type=submit>Submit</button></td>
</tr>

</table>
</form>
</body>
</html>
<script>document.form.name.focus();</script>
EOH
