#!/usr/bin/perl
use strict;
use warnings;
use CGI;
my $q = CGI->new();
print $q->header();

use Date::Simple qw/
    today
/;
my $d8 = today->as_d8();

use BeeUtil qw/
    word_score
    trim
/;

use Bee_DBH qw/
    $dbh
    get_person
/;

my %params = $q->Vars();

my ($ip_id, $person_id, $name, $location) = get_person();
my $sth_ins_clue = $dbh->prepare(<<'EOS');

    INSERT
      INTO bee_clue
           (person_id, date, word, clue)
    VALUES (?, ?, ?, ?)

EOS

# we choose ~ and ^ as characters
# that are very unlikely to be used
# in the clue - what if they are?
my $clues = join '',
            map {
                my $k = $_;
                my $w = $k; $w =~ s{_clue\z}{}xms;
                my $clue = $params{$k};
                $clue = trim($clue);
                $sth_ins_clue->execute($person_id, 'CP', $w, $clue);
                $clue =~ s{"}{'}xmsg;        # double quote => single quote
                "$w^$clue~"
            }
            grep { 
                m/_clue\z/xms 
                &&
                $params{$_} =~ m{\S}   # why not just $params{$_}?
            }
            keys %params;
my $seven = $params{seven};
my $center = $params{center};
my $words = $params{words};
my $pangrams = $params{pangrams};
my %is_pangram = map { $_ => 1 } split ' ', $pangrams;
my @words = split ' ', $words;
my $nwords = @words;
my $points = 0;
for my $w (@words) {
    $points += word_score($w, $is_pangram{$w});
}

print <<"EOH";
<html>
<head>
<link rel='stylesheet' type='text/css' href='http://logicalpoetry.com/nytbee/cgi_style.css'/>
</head>
<body>
<h1>Making an NYT Type<br>Spelling Bee Puzzle<br>Step <span class=red>5</span></h1>
<form name=form action=final_mkpuz method=POST>
<input type=hidden name=seven value='$seven'>
<input type=hidden name=center value='$center'>
<input type=hidden name=words value='$words'>
<input type=hidden name=pangrams value='$pangrams'>
<input type=hidden name=clues value="$clues">
<input type=hidden name=created value='$d8'>
Words: $nwords, Points: $points<br>
Pangrams: <span class=green>$pangrams</span><p>
Finally, provide some information about yourself.
<p>
<table cellpadding=5>

<tr>
<th>Name</th>
<td><input type=text name=name value="$name" size=40></td>
</tr>

<tr>
<th>Location</th>
<td><input type=text name=location value="$location" size=40></td>
</tr>

<tr>
<th>&nbsp;</th>
<td style="text-align: left"><button class=submit type=submit>Submit</button></td>
</tr>

</table>
</form>
</body>
</html>
<script>document.form.name.focus();</script>
</form>
EOH
