#!/bin/bash
rm -f /tmp/cgi.tar
tar cvf /tmp/cgi.tar  \
BeeUtil.pm \
BeeDBM.pm \
comments.txt \
SvgHex.pm \
free_sn \
BeeColor.pm \
BeeClues.pm \
clues.pl \
cron_jon \
final_mkpuz.pl \
get_clues.pl \
get_nytbee.pl \
nyt_puzzles.txt \
nytbee_list.pl \
nytbee_fcp.pl \
nytbee_time.pl \
nytbee_activity.pl \
nytbee_log.pl \
nytbee_bbx.pl \
indexize \
de_indexize \
get_pangrams \
gwords.pl \
load_nytbee \
mkpuz_tally.pl \
nytbee \
nytbee_archive \
nytbee.pl \
rand_nytbee.pl \
same_nytbee.pl \
search_nytbee.pl \
tally_nytbee.pl \
mknyt \
nytbee_mkclues.pl \
nytbee_mkclues2.pl \
Bee_DBH.pm \
nytbee_clue_dates.pl \
nytbee_get_clues.pl \
nytbee_get_cluers.pl \
nytbee_clues_by.pl \
nytbee_define.pl \
nytbee_cw.pl \
nytbee_top.pl \
nytbee_wp.pl \
who_played \
mktar \
go \
dump_dbm \
set_dbm \
del_dbm \
edit_cp.pl \
edit_cp_clues.pl \
edit_cp_get_clues.pl \
edit_cp_final.pl \
cp_del_clues.pl \
goo10k-47.txt \
set_uuid.pl \
osx_usd_words-47.txt \
word_pangram.pl \
dynamic.pl \
rand5.pl \
admin.pl \
show_activity.pl \
ipstack.txt \
definitions.txt \
messages \
mkforum \
show_forum.pl \
forum_flag.pl \
fmod.pl \
get_post.pl \
status.pl \
fix_cur \
ini \
fin \
buddy.txt

# these will not change
#JSON/PP.pm
#Date
