#!/bin/bash
rm /tmp/cgi.tar
tar cvf /tmp/cgi.tar  \
BeeUtil.pm \
BeeClues.pm \
clues \
cron_jon \
final_mkpuz \
get_clues \
get_nytbee \
get_pangrams \
gwords \
load_nytbee \
mkpuz_tally \
nytbee \
nytbee_archive \
nytbee.pl \
rand_nytbee \
same_nytbee \
search_nytbee \
tally_nytbee \
mknyt \
nytbee_mkclues \
nytbee_mkclues \
nytbee_mkclues2 \
Bee_DBH.pm \
nytbee_clue_dates \
nytbee_get_clues \
nytbee_get_cluers \
nytbee_clues_by \
nytbee_define \
mktar \
go \
dump_dbm \
edit_cp \
edit_cp_clues \
edit_cp_final

# these will not change
#JSON/PP.pm
#Date
