#!/usr/bin/perl
use strict;
use warnings;

# a poor man's database
use DB_File;
my %puzzle;
tie %puzzle, 'DB_File', 'nyt_puzzles.dbm';
print "Content-Type: text/html; charset=ISO-8859-1\n\n";
for my $dt (sort keys %puzzle) {
    print "$dt $puzzle{$dt}\n";
}
