#!/usr/bin/perl
use strict;
use warnings;

print "Content-Type: text/html; charset=ISO-8859-1\n\n";

my $date = $ENV{PATH_INFO};
$date =~ s{\A /}{}xms;

use Bee_DBH qw/
    $dbh
/;

my $sth = $dbh->prepare(<<'EOH');
    
    SELECT word, clue
      FROM bee_clue
     WHERE date = ?

EOH
$sth->execute($date);
my %clues;
while (my ($word, $clue) = $sth->fetchrow_array()) {
    push @{$clues{$word}}, $clue;
}
use Data::Dumper;
$Data::Dumper::Terse = 1;
print Dumper(\%clues);
