#!/usr/bin/perl
use strict;
use warnings;

# a poor man's database
use DB_File;
my %puzzle;
tie %puzzle, 'DB_File', 'nyt_puzzles.dbm';

my ($min, $hour, $day, $month) = (localtime)[ 1..4 ];
++$month;
open my $out, '>>', 'nytbee_log.txt';
printf {$out} "%02d/%02d %02d:%02d $ENV{REMOTE_ADDR} archive\n",
              $month, $day, $hour, $min;
close $out;

print "Content-Type: text/html; charset=ISO-8859-1\n\n";
for my $dt (sort keys %puzzle) {
    print "$dt $puzzle{$dt}\n";
}
