#!/usr/bin/perl
use strict;
use warnings;

# no need to use CGI
print "Content-Type: text/html; charset=ISO-8859-1\n\n";

my $ip_id = $ENV{PATH_INFO};
$ip_id =~ s{\A /}{}xms;
$ip_id =~ s{_}{ }xmsg;

open JON, '>/tmp/jon';
print JON "ip_id = $ip_id\n"; close JON;

use Bee_DBH qw/
    $dbh
/;

my $sth = $dbh->prepare(<<'EOS');

    SELECT id
      FROM bee_person
     WHERE ip_id = ?

EOS
$sth->execute($ip_id);
my ($id) = $sth->fetchrow_array();

my $sth_dates = $dbh->prepare(<<'EOH');

    SELECT distinct date
      FROM bee_clue
     WHERE person_id = ?
  ORDER BY date

EOH
$sth_dates->execute($id);
my @dates;
while (my ($date) = $sth_dates->fetchrow_array()) {
    push @dates, $date;
}
print map {
          m{\A ..(..)(..)(..)}xms;
          "$2/$3/$1<br>\n";
      }
      @dates;
