#!/usr/bin/perl
use strict;
use warnings;
sub oops {
    die "usage: set_dbm file.dbm key val\n";
}
oops unless @ARGV == 3;
my ($hash_file, $key, $val) = @ARGV;
oops unless $hash_file && $hash_file =~ m{\A \S+[.]dbm \z}xms;
oops unless defined $key && defined $val;
use DB_File;
my %hash;
tie %hash, 'DB_File', $hash_file;
$hash{$key} = $val;
