#!/usr/bin/perl
use strict;
use warnings;
sub oops {
    die "usage: set_dbm file.dbm key val\n";
}
oops unless @ARGV == 3;
my ($hash_file, $key, $val) = @ARGV;
if ($hash_file !~ m{\A \S+[.]dbm \z}xms) {
    $hash_file .= '.dbm';
}
oops unless -f $hash_file;
oops unless defined $key && defined $val;
if ($val =~ m{\A f:(\S+) \z}xms) {
    my $fname = $1;
    open my $in, '<', $fname or die "cannot open $fname: $!\n";
    local $/;
    $val = <$in>;
    chomp $val;
    close $in;
}
use DB_File;
my %hash;
tie %hash, 'DB_File', $hash_file or die "no tie!";
$hash{$key} = $val;
use BeeUtil 'JON';
JON "key $key val $val => $hash{$key}";
